const test=require('node:test'),assert=require('node:assert/strict'),D=require('../ai-data.js');
globalThis.HorasAIData=D;Object.defineProperty(globalThis,'navigator',{value:{onLine:true},configurable:true});
const facts={period:'2026-10',gross:100,deductions:10,net:90,normalHours:10,holidayHours:0,extraHours:0,normalRate:10,holidayRate:15,extraRate:0,complete:true,missing:[]};
test('structured data rejects missing/wrong types, infinities, impossible dates and dangerous properties',()=>{assert.deepEqual(D.normalizePayroll(facts),facts);for(const p of [{...facts,period:'2026-13'},{...facts,net:'90'},{...facts,normalHours:1001},{...facts,net:NaN},{...facts,complete:1},{...facts,missing:[{}]},{...facts,extraRate:undefined},JSON.parse('{"__proto__":{"bad":true}}')])assert.throws(()=>D.normalizePayroll(p));assert.equal({}.bad,undefined);});
test('comparison has three outcomes, requires correct period and explicit confirmation; no state edits',()=>{const expected={...facts},before=JSON.stringify(expected);assert.equal(D.comparePayroll(facts,expected).status,'unknown');assert.equal(D.comparePayroll(facts,expected,true).status,'match');const r=D.comparePayroll({...facts,net:80},expected,true);assert.equal(r.status,'different');assert.equal(r.differences[0].expected,90);assert.equal(D.comparePayroll({...facts,complete:false},expected,true).status,'unknown');assert.equal(D.comparePayroll({...facts,net:null},expected,true).status,'unknown');assert.equal(D.comparePayroll({...facts,period:'2026-09'},expected,true).status,'unknown');assert.equal(JSON.stringify(expected),before);});
test('redaction attempts identifiers locally without removing ordinary salary numbers',()=>{const text='Nombre: Persona Ficticia\nDNI 12345678Z email persona@example.invalid\nCuenta ES12 1234 5678 9012 3456 7890\nBruto: 1200,25 neto: 1080,20';const r=D.redact(text,['Persona Ficticia']);for(const v of ['Persona Ficticia','12345678Z','persona@example.invalid','1234 5678'])assert(!r.includes(v));assert(r.includes('1200,25'));});
const file={size:200,arrayBuffer:async()=>new TextEncoder().encode('%PDF-fixture').buffer};
function pdfLibrary(pages){let destroyed=false;return {get destroyed(){return destroyed;},getDocument(options){assert.equal(options.isEvalSupported,false);return {promise:Promise.resolve({numPages:pages.length,getPage:async n=>({getTextContent:async()=>({items:[{str:pages[n-1],transform:[0,0,0,0,0,10]}]})}),destroy:async()=>{destroyed=true;}})}}};}
test('reads complete multipage text beyond 3000 characters, destroys PDF',async()=>{const lib=pdfLibrary(['Conceptos salariales '+ 'x'.repeat(4000),'Periodo octubre 2026 bruto 100 neto 90']);const r=await D.extractPDF(file,lib);assert(r.text.length>4000);assert(r.text.includes('neto 90'));assert.equal(r.pages,2);assert(lib.destroyed);});
test('rejects scanned/incomplete, unreadable, oversized/too long documents rather than inventing or cropping',async()=>{for(const pages of [[''],['Nómina con texto suficiente para leer correctamente',''],Array(41).fill('texto válido para una nómina completa'),['Nómina '+'x'.repeat(120001)]]){const lib=pdfLibrary(pages);await assert.rejects(D.extractPDF(file,lib));assert(lib.destroyed);}await assert.rejects(D.extractPDF({...file,size:11*1024*1024},pdfLibrary(['texto válido'])));await assert.rejects(D.extractPDF({...file,arrayBuffer:async()=>new TextEncoder().encode('<html>').buffer},pdfLibrary(['texto válido'])));});
async function harness(response='Respuesta ficticia',opts={}){const {createService}=await import('../ai-service.js');let calls=0,request,config,signouts=0;const auth={currentUser:null},S={string:x=>x,number:x=>x,boolean:()=>({}),array:x=>x,object:x=>x};let reply=async()=>response;
 const loader=async()=>[{initializeApp:(options,name)=>({options,name})},{initializeAuth:()=>auth,inMemoryPersistence:{},updateCurrentUser:async(a,u)=>{a.currentUser=u;},signOut:async a=>{signouts++;a.currentUser=null;}},{initializeAppCheck(){},ReCaptchaEnterpriseProvider:class{}},{Schema:S,getAI:()=>({}),GoogleAIBackend:class{},getGenerativeModel:(a,c)=>{config=c;return {generateContent:async p=>{calls++;request=p;const text=await reply();return {response:{text:()=>text}};}}}}];
 const service=createService(loader,opts),input={mode:'chat',question:'horas',context:{recordedHours:8.25},options:{projectId:'fixture'},user:{uid:'fixture'},session:'one',currentSession:()=> 'one'};
 return {service,input,auth,get calls(){return calls;},get request(){return request;},get config(){return config;},get signouts(){return signouts;},set reply(v){reply=v;}};
}
test('service uses only Gemini/App Check and validates payroll JSON/schema',async()=>{const h=await harness();h.reply=()=>JSON.stringify(facts);assert.deepEqual(await h.service.query({...h.input,mode:'payroll',text:'Texto ficticio'}),facts);assert.equal(h.config.model,'gemini-3.1-flash-lite');assert.equal(h.config.generationConfig.responseMimeType,'application/json');assert(!JSON.stringify(h.request).includes('recordedHours'));h.reply=()=>'{bad}';await assert.rejects(h.service.query({...h.input,mode:'payroll'}),e=>e.kind==='invalid');});
test('one send, no automatic retries; session changes discard pending result',async()=>{const h=await harness();let resolve;h.reply=()=>new Promise(r=>resolve=r);const pending=h.service.query(h.input);await new Promise(r=>setImmediate(r));await assert.rejects(h.service.query(h.input),e=>e.kind==='busy');h.service.invalidate();resolve('respuesta');await assert.rejects(pending,e=>e.kind==='cancelled');assert.equal(h.calls,1);assert.equal(h.signouts,1);});
test('timeout suppresses late response and keeps lock until SDK settles',async()=>{const h=await harness('late',{timeout:10});let resolve;h.reply=()=>new Promise(r=>resolve=r);await assert.rejects(h.service.query(h.input),e=>e.kind==='timeout');await assert.rejects(h.service.query(h.input),e=>e.kind==='busy');resolve('late');await new Promise(r=>setImmediate(r));assert.equal(h.calls,1);});
test('offline/missing session/SDK failure/quota/permission and invalid answers have distinct bounded errors',async()=>{const h=await harness();navigator.onLine=false;await assert.rejects(h.service.query(h.input),e=>e.kind==='offline');navigator.onLine=true;await assert.rejects(h.service.query({...h.input,user:null}),e=>e.kind==='unauthenticated');const {classify,errorMessage,createService}=await import('../ai-service.js');for(const [status,kind] of [[429,'quota'],[403,'permission'],[401,'unauthenticated']])assert.equal(classify({code:'ai/fetch-error',customErrorData:{status}}).kind,kind);assert.equal(classify({name:'AbortError'}).kind,'timeout');h.reply=()=>'';await assert.rejects(h.service.query(h.input),e=>e.kind==='invalid');const bad=createService(async()=>{throw Error('SDK unavailable')});await assert.rejects(bad.query(h.input),e=>e.kind==='unavailable');assert(!errorMessage({kind:'permission',secret:'bad'}).includes('bad'));});
