const test=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js');
const defaults={userName:'',hideMoney:false,rateNormal:10,plusFestivo:5,rateExtra:20,profile:'ett',sintaxUnlocked:false,deductions:[{id:'d1',name:'IRPF',pct:10}]};
const copy=C.copy;
const fixture=()=>C.validateBackup({config:defaults,data:{'2026-01':{days:{1:{type:'normal',hours:8.25},2:{type:'festivo',hours:9.5},3:{type:'descanso',hours:0}}}}},defaults);
test('legacy migration preserves every day and marks unknown historical rates',()=>{const p=fixture();assert.equal(p.data['2026-01'].days[1].hours,8.25);assert.equal(p.data['2026-01'].historicalStatus,'unknown');assert.deepEqual(p.data['2026-01'].rateConfig,C.financial(defaults));});
test('monthly gross, percentages, net and daily totals use one calculation',()=>{const p=fixture(),r=C.calculate(p.data,p.config,2026,0);assert.equal(r.bruto,225);assert.equal(r.totalDed,22.5);assert.equal(r.neto,202.5);assert.equal(r.diasDesc,1);assert.equal(r.hNormal+r.hFestivo,17.75);assert.equal([1,2,3].reduce((s,d)=>s+C.daily(p.data,p.config,2026,0,d).bruto,0),r.bruto);});
test('changing current rates/deductions cannot change a migrated period',()=>{const p=fixture(),before=C.calculate(p.data,p.config,2026,0);p.config.rateNormal=100;p.config.deductions[0].pct=30;assert.deepEqual(C.calculate(p.data,p.config,2026,0),before);});
test('reject invalid dates/hours/types/rates/percentages before altering source',()=>{for(const mutate of [p=>p.data['2026-02']={days:{30:{type:'normal',hours:8}}},p=>p.data['2026-01'].days[1].hours=25,p=>p.data['2026-01'].days[1].hours='8',p=>p.data['2026-01'].days[1].type='evil',p=>p.config.rateNormal=-1,p=>p.config.deductions[0].pct=101]){const p=fixture(),before=copy(p);mutate(p);const input=JSON.stringify(p);assert.throws(()=>C.validateBackup(p,defaults));assert.equal(JSON.stringify(p),input);assert.equal(before.data['2026-01'].days[1].hours,8.25);}});
test('reject dangerous properties; HTML remains inert text after escaping',()=>{assert.throws(()=>C.validateBackup(JSON.parse('{"config":{},"data":{},"__proto__":{"polluted":true}}'),defaults));const p=fixture();p.config.deductions[0].name='<img src=x onerror=alert(1)>';const r=C.validateBackup(p,defaults);assert.equal(r.config.deductions[0].name,p.config.deductions[0].name);assert.match(C.escapeHTML(r.config.deductions[0].name),/&lt;img/);assert.equal({}.polluted,undefined);});
function week(y,m,start,hours=10){const data={};for(let i=0;i<5;i++){const date=new Date(y,m,start+i),mk=C.monthKey(date.getFullYear(),date.getMonth());data[mk]||={days:{},rateConfig:C.financial({...defaults,profile:'sintax',sintaxUnlocked:true}),historicalStatus:'confirmed'};data[mk].days[date.getDate()]={type:'normal',hours};}return data;}
test('Sintax crosses months: 40 hour threshold, reverse assignment, next-month pay',()=>{const data=week(2026,7,31),cfg={...defaults,profile:'sintax',sintaxUnlocked:true}; // Monday Aug 31 through Sep 4.
 assert.equal(C.extraMap(data,2026,7)[31],undefined);assert.equal(C.extraMap(data,2026,8)[4],10);const aug=C.calculate(data,cfg,2026,7),sep=C.calculate(data,cfg,2026,8),oct=C.calculate(data,cfg,2026,9);assert.equal(aug.bruto,100);assert.equal(sep.bruto,300);assert.equal(oct.hExtra,10);assert.equal(oct.brutoExtra,200);assert.equal(sep.hExtraGen,10);data['2026-09'].days[4]=null;assert.equal(C.calculate(data,cfg,2026,9).hExtra,0);});
test('Sintax crosses years; holiday hours count in threshold but remain paid as holiday',()=>{const cfg={...defaults,profile:'sintax',sintaxUnlocked:true},data=week(2025,11,29);data['2026-01'].days[2].type='festivo';assert.equal(C.extraMap(data,2025,11)[31],undefined);assert.equal(C.extraMap(data,2026,0)[1],10);const jan=C.calculate(data,cfg,2026,0);assert.equal(jan.hNormalPaid,0);assert.equal(jan.brutoFestivo,150);assert.equal(C.calculate(data,cfg,2026,1).hExtra,10);data['2025-12'].days[29].hours=8;assert.equal(C.extraMap(data,2026,0)[1],8);});
test('whole-holiday week preserves existing assumption: no normal hours to assign extra',()=>{const cfg={...defaults,profile:'sintax',sintaxUnlocked:true},data=week(2026,0,5);for(const e of Object.values(data['2026-01'].days))e.type='festivo';assert.deepEqual(C.extraMap(data,2026,0),{});assert.equal(C.calculate(data,cfg,2026,0).brutoFestivo,750);});
test('hour color remains progressive at exact 9.5 and 12 thresholds',()=>{assert.equal(C.hoursColor(9.49),'#E8EDF7');assert.equal(C.hoursColor(9.5),'rgb(255,176,79)');assert.notEqual(C.hoursColor(10),C.hoursColor(11));assert.equal(C.hoursColor(12),'rgb(255,112,112)');assert.equal(C.hoursColor(24),C.hoursColor(12));});
test('independent atomic operations commute and deletion remains a tombstone',()=>{const p=fixture(),a=[{path:['data','2026-01','days','1'],value:null}],b=[{path:['data','2026-01','days','2'],value:{type:'normal',hours:4}}];assert.deepEqual(C.applyOps(C.applyOps(p,a),b),C.applyOps(C.applyOps(p,b),a));assert.equal(C.applyOps(p,a).data['2026-01'].days[1],null);});
const facts={period:'2026-01',gross:225,deductions:22.5,net:202.5,normalHours:8.25,holidayHours:9.5,extraHours:0,normalRate:10,holidayRate:15,extraRate:20,complete:true,missing:[]};
test('payroll comparison has match/difference/unknown outcomes with explicit limits',()=>{const p=fixture();assert.equal(C.comparePayroll(facts,p.data,p.config).status,'unknown');p.data['2026-01'].historicalStatus='confirmed';p.data['2026-01'].closed=true;assert.equal(C.comparePayroll(facts,p.data,p.config).status,'match');assert.equal(C.comparePayroll({...facts,net:200},p.data,p.config).status,'different');assert.equal(C.comparePayroll({...facts,period:null},p.data,p.config).status,'unknown');assert.equal(C.comparePayroll({...facts,complete:false,missing:['Base ausente']},p.data,p.config).status,'unknown');assert.throws(()=>C.normalizePayroll({...facts,gross:'225'}));});
test('local minimization removes usual DNI/NIE, account, email and named identity lines',()=>{const r=C.redactPayroll('Nombre: Persona ficticia\nDNI: 12345678Z\nIBAN ES9121000418450200051332\nuno@example.invalid\nBruto 225');assert(!r.includes('Persona ficticia'));assert(!r.includes('12345678Z'));assert(!r.includes('ES912100'));assert(!r.includes('uno@example'));assert(r.includes('Bruto 225'));});
