const test=require('node:test'),assert=require('node:assert/strict');global.HorasCore=require('../core.js');const C=HorasCore,{create}=require('../sync.js');
const defaults={userName:'',hideMoney:false,rateNormal:10,plusFestivo:5,rateExtra:20,profile:'ett',sintaxUnlocked:false,deductions:[]},blank=()=>({schemaVersion:3,config:C.copy(defaults),data:{}}),tick=()=>new Promise(r=>setImmediate(r));
function server(){const docs=new Map(),listeners=[],writes=[];let deny=false,hold=null;
 const emit=uid=>listeners.filter(x=>x.uid===uid).forEach(x=>x.cb({exists:docs.has(uid),data:()=>C.copy(docs.get(uid)),metadata:{hasPendingWrites:false,fromCache:false}}));
 const db={collection:()=>({doc:uid=>({onSnapshot(opts,cb){const l={uid,cb};listeners.push(l);queueMicrotask(()=>emit(uid));return()=>listeners.splice(listeners.indexOf(l),1);},async set(p,{mergeFields}){if(deny)throw {code:'permission-denied'};if(hold)await hold;const ops=mergeFields.map(f=>{let v=p;for(const k of f.parts)v=v[k];return {path:f.parts,value:v};});docs.set(uid,C.applyOps(docs.get(uid)||blank(),ops));writes.push({uid,ops});emit(uid);},async get(){return {exists:docs.has(uid),data:()=>C.copy(docs.get(uid)),metadata:{fromCache:false}};}})})};
 return {db,docs,writes,emit,deny:v=>deny=v,hold:v=>hold=v};}
function device(s,store=new Map()){let p=blank(),statuses=[];const storage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};const engine=create({defaults,getState:()=>p,apply:x=>p=x,onStatus:(...x)=>statuses.push(x),storage,db:s.db,FieldPath:class{constructor(...parts){this.parts=parts;}}});engine.load();return {engine,store,statuses,get p(){return p;},edit(day,h){p.data['2026-10']||={days:{},rateConfig:C.financial(defaults),historicalStatus:'confirmed'};p.data['2026-10'].days[day]=h===null?null:{type:'normal',hours:h};engine.save();}};}
async function login(d,uid='one'){d.engine.switchAccount({uid});await tick();}
test('two simulated devices preserve independent simultaneous days',async()=>{const s=server(),a=device(s),b=device(s);await login(a);await login(b);a.edit(1,8);b.edit(2,9);await tick();await tick();assert.equal(s.docs.get('one').data['2026-10'].days[1].hours,8);assert.equal(s.docs.get('one').data['2026-10'].days[2].hours,9);assert.deepEqual(a.p.data,b.p.data);assert.equal(a.engine.pending().length,0);});
test('offline edits survive restart; remote updates cannot overwrite pending work',async()=>{const s=server(),a=device(s),b=device(s);await login(a);await login(b);a.engine.setOnline(false);a.edit(1,7);b.edit(2,10);await tick();assert.equal(a.p.data['2026-10'].days[1].hours,7);const restarted=device(s,a.store);restarted.engine.setOnline(false);await login(restarted);assert.equal(restarted.p.data['2026-10'].days[1].hours,7);assert.equal(restarted.p.data['2026-10'].days[2].hours,10);restarted.engine.setOnline(true);await tick();await tick();assert.equal(s.docs.get('one').data['2026-10'].days[1].hours,7);});
test('edit vs deletion uses last server commit; tombstone does not resurrect on reconnect',async()=>{const s=server(),a=device(s),b=device(s);await login(a);await login(b);a.edit(1,8);await tick();b.engine.setOnline(false);b.edit(2,6);a.edit(1,null);await tick();b.engine.setOnline(true);await tick();assert.equal(s.docs.get('one').data['2026-10'].days[1],null);b.edit(1,9);await tick();assert.equal(s.docs.get('one').data['2026-10'].days[1].hours,9);a.edit(1,null);await tick();assert.equal(b.p.data['2026-10'].days[1],null);});
test('denied writes stay journaled without automatic unlimited retries',async()=>{const s=server(),a=device(s);await login(a);s.deny(true);a.edit(1,8);await tick();assert.equal(a.engine.pending().length,3);assert.equal(a.statuses.at(-1)[0],'error');s.deny(false);await a.engine.flush();await tick();assert.equal(a.engine.pending().length,0);assert.equal(s.docs.get('one').data['2026-10'].days[1].hours,8);});
test('switching accounts and stale acknowledgement cannot mix journals or data',async()=>{const s=server(),a=device(s);await login(a);let release;s.hold(new Promise(r=>release=r));a.edit(1,8);await login(a,'two');assert.deepEqual(a.p.data,{});release();await tick();await tick();assert.deepEqual(a.p.data,{});assert.equal(s.docs.has('two'),false);await login(a,'one');assert.equal(a.p.data['2026-10'].days[1].hours,8);a.engine.switchAccount(null);assert.deepEqual(a.p.data,{});});
test('cloud pull protects old local data and rejects pending local changes',async()=>{const s=server(),a=device(s);await login(a);a.engine.setOnline(false);a.edit(1,8);await assert.rejects(a.engine.pull(),/pendientes/);a.engine.setOnline(true);await tick();await tick();await a.engine.pull();assert(a.engine.recovery());});
test('legacy local copy is preserved and never implicitly uploaded to another account',async()=>{const s=server(),raw=JSON.stringify({...blank(),data:{'2026-10':{days:{1:{type:'normal',hours:8}}}}}),store=new Map([['horas-app-v2',raw]]),a=device(s,store);assert.equal(a.p.data['2026-10'].days[1].hours,8);assert.equal(store.get('horas-original-v2'),raw);await login(a);assert.deepEqual(a.p.data,{});assert.equal(s.writes.length,0);a.engine.switchAccount(null);assert.equal(a.p.data['2026-10'].days[1].hours,8);});
