// Actual inline application in a minimal DOM adapter. No real Firebase/AI call.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const html=fs.readFileSync(new URL('../index.html',`file://${__filename}`),'utf8');
const source=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].at(-1)[1];
const config={rateNormal:10,plusFestivo:5,rateExtra:20,userName:'',profile:'ett',sintaxUnlocked:false,hideMoney:false,deductions:[{id:'d1',name:'IRPF',pct:10}]};
const payload={config,data:{'2026-10':{days:{1:{type:'normal',hours:8.25},2:{type:'festivo',hours:10.75},3:{type:'normal',hours:12},4:{type:'descanso',hours:0}}}}};
class Element{constructor(){this.innerHTML='';this.style={};this.classList={add(){}};this.value='';}querySelector(){return new Element();}querySelectorAll(){return [];}focus(){}replaceWith(x){this.replacement=x;}setAttribute(k,v){this[k]=v;}}
function app(storage=new Map([['horas-app-v2',JSON.stringify(payload)]])){
 const elements=new Map(),el=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);};let requests=0,fetcher=async()=>({ok:true,text:async()=>'<img src=x onerror="bad()"> 900 €'});
 const D=class extends Date{constructor(...a){super(...(a.length?a:['2026-10-08T12:00:00Z']));}static now(){return new Date('2026-10-08T12:00:00Z').getTime();}};
 const ctx=vm.createContext({Date:D,Intl,Blob,console:{error(){},warn(){}},document:{activeElement:null,getElementById:el,createElement:()=>new Element()},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},navigator:{},setTimeout:()=>0,clearTimeout(){},matchMedia:()=>({matches:true}),alert(){},confirm:()=>true,Chart:class{constructor(e,c){ctx.chartOptions=c;}destroy(){}},fetch:async(...a)=>{requests++;return fetcher(...a);},FileReader:class{readAsText(f){this.result=f.text;this.onload();}}});ctx.window=ctx;vm.runInContext(source,ctx);return {ctx,storage,el,run:s=>vm.runInContext(s,ctx),get requests(){return requests;},set fetcher(v){fetcher=v;}};
}
test('hide all monthly amounts/projection and daily rate while retaining hours and days',()=>{const a=app();a.run('selectDay(1)');assert(a.el('app').innerHTML.includes('363,75'));a.run('toggleMoney()');const m=a.el('app').innerHTML,e=a.el('editor-container').innerHTML;assert(!m.includes('363,75'));assert(!m.includes('36,38'));assert(m.includes('31 h'));assert(m.includes('•••• €'));assert(e.includes('•••• €/h'));assert(!e.includes('10.00 €/h'));assert(m.includes('aria-label="Mostrar importes"'));assert(m.includes('aria-pressed="true"'));});
test('privacy persists after reload/navigation/remote sync/import; no cloud save from eye',()=>{const a=app();a.run('toggleMoney();switchTab("anual");renderChart()');assert.equal(a.ctx.chartOptions.data.datasets[0].label,'Horas');assert.equal(a.ctx.chartOptions.data.datasets[0].data[9],31);assert.equal(a.ctx.chartOptions.options.animation,false);const b=app(a.storage);assert.equal(b.run('state.config.hideMoney'),true);b.ctx.incoming=structuredClone(payload);b.run('applyRemote(incoming)');assert.equal(b.run('state.config.hideMoney'),true);b.run('importBackup({target:{files:[{text:JSON.stringify(incoming)}]}})');assert.equal(b.run('state.config.hideMoney'),true);assert.equal(a.requests,0);assert(!('hideMoney' in b.run('cloudConfig()')));});
test('old local hideMoney migrates once, unrelated data and preferences remain intact',()=>{const p=structuredClone(payload);p.config.hideMoney=true;const raw=JSON.stringify(p),store=new Map([['horas-app-v2',raw],['unrelated-app','keep']]),a=app(store);assert.equal(a.run('state.config.hideMoney'),true);assert.equal(store.get('horas-hide-money'),'1');assert.equal(store.get('horas-app-v2'),raw);assert.equal(store.get('unrelated-app'),'keep');});
test('hide AI history/payroll result and block new requests while hidden',async()=>{const a=app();a.run('state.chatMsgs=[{role:"bot",text:"1234 euros"}];state.nomina.result={resumen:"Nómina 999 euros"};toggleMoney();switchTab("ia")');assert(!a.el('app').innerHTML.includes('1234'));assert(!a.el('app').innerHTML.includes('999'));assert(a.el('app').innerHTML.includes('disabled'));await a.run('sendChat("pregunta")');await a.run('handleNominaUpload({target:{files:[{}]}})');assert.equal(a.requests,0);});
test('pending AI response is discarded after hiding money',async()=>{const a=app();let resolve;a.fetcher=()=>new Promise(r=>resolve=r);const pending=a.run('sendChat("consulta")');a.run('toggleMoney()');resolve({ok:true,text:async()=>'<img src=x onerror=alert(1)> 999 €'});await pending;assert.equal(a.run('state.chatMsgs.length'),0);assert(!a.el('app').innerHTML.includes('999'));});
test('user/AI/retention/imported text is escaped in template and attribute contexts',async()=>{const a=app();a.run('state.config.userName="\\\"><img src=x onerror=bad()>";state.config.deductions[0].name="<svg onload=bad()>";switchTab("ajustes")');assert(a.el('app').innerHTML.includes('&lt;img'));assert(!a.el('app').innerHTML.includes('<img'));assert(a.el('app').innerHTML.includes('&lt;svg'));a.run('switchTab("ia")');await a.run('sendChat("<script>bad()</script>")');assert(!a.el('app').innerHTML.includes('<script>'));assert(a.el('app').innerHTML.includes('&lt;script&gt;'));assert(a.el('app').innerHTML.includes('&lt;img'));});
test('hour colors preserve 9.5→12 thresholds/progression in calendar and editor',()=>{const a=app();assert.equal(a.run('hoursColor(9.49)'),'#E8EDF7');assert.equal(a.run('hoursColor(9.5)'),'rgb(255,176,79)');assert.notEqual(a.run('hoursColor(10)'),a.run('hoursColor(11)'));assert.equal(a.run('hoursColor(12)'),'rgb(255,128,128)');assert.equal(a.run('hoursColor(24)'),a.run('hoursColor(12)'));a.run('selectDay(2)');assert(a.el('editor-container').innerHTML.includes('rgb(255,152,104)'));assert(a.el('calendar-grid').innerHTML.includes('rgb(255,152,104)'));});
test('exports retain economic figures when hidden and clearly warn about their contents',()=>{const a=app();a.run('toggleMoney();openExportModal()');assert(a.el('modal-export-content').innerHTML.includes('contiene datos económicos'));const visible=a.run('const doc=createPdfDoc();buildMonthReport(doc,2026,9);assemblePdf(doc.pages)');assert(visible.includes('363,75'));a.run('switchTab("ajustes")');assert(a.el('app').innerHTML.includes('copias contienen datos económicos'));});
test('saving and remote updates do not repeat screen-entry animation; zoom/reduced-motion available',()=>{const a=app();assert(a.el('app').querySelector('.tab-content'));assert(a.run('lastRenderedTab')==='mes');a.run('selectDay(6);saveDay()');assert(a.run('lastRenderedTab')==='mes');assert(!html.includes('user-scalable=no'));assert(html.includes('prefers-reduced-motion: reduce'));assert(!/\.tab-content[^}]*animation:/.test(html));assert(html.includes('min-height: 44px'));});
function luminance(rgb){return rgb.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);}
function ratio(a,b){const l=[luminance(a),luminance(b)].sort((a,b)=>b-a);return (l[0]+.05)/(l[1]+.05);}
test('small text/hour scale have WCAG AA contrast on actual dark/tinted backgrounds',()=>{const a=app(),bg=[17,21,31],card=[23,28,42],normal=bg.map((v,i)=>v*.82+[79,163,255][i]*.18),holiday=bg.map((v,i)=>v*.8+[255,176,79][i]*.2),rest=bg.map((v,i)=>v*.8+[193,202,219][i]*.2),editor=card.map((v,i)=>v*.92+[123,232,168][i]*.08);for(const back of [bg,card,normal,holiday,rest,editor]){assert(ratio([175,184,204],back)>=4.5);for(let h=9.5;h<=12.05;h+=.05){const color=a.run(`hoursColor(${h})`).match(/\d+/g).map(Number);assert(ratio(color,back)>=4.5);}}});

test('numeric fields from unvalidated legacy imports cannot inject HTML attributes',()=>{const a=app();a.run('state.config.rateNormal=\"\\\"><img src=x onerror=bad()>\";state.config.deductions[0].pct=\"\\\"><img src=x onerror=bad()>\";switchTab(\"ajustes\")');assert(!a.el('app').innerHTML.includes('<img'));assert(a.el('app').innerHTML.includes('&lt;img'));const b=app();b.run('state.allData[\"2026-10\"].days[1].hours=\"\\\"><img src=x onerror=bad()>\";selectDay(1)');assert(!b.el('editor-container').innerHTML.includes('<img'));assert(b.el('editor-container').innerHTML.includes('&lt;img'));});

test('calendar cells contain only day and hours, with distinct backgrounds and accessible day types',()=>{const a=app(),grid=a.el('calendar-grid').innerHTML;for(const [day,type,count] of [[1,'Normal',2],[2,'Festivo',2],[4,'Descanso',1]]){const cell=grid.match(new RegExp(`id="day-btn-${day}"[\\s\\S]*?<\\/button>`))[0];assert(cell.includes(type));assert.equal((cell.match(/<span/g)||[]).length,count);assert(!/>(?:N|F|D|D · zZ)<\/span>/.test(cell));}assert.notEqual(a.run('TYPES.festivo.bg'),a.run('TYPES.descanso.bg'));assert.notEqual(a.run('TYPES.normal.bg'),a.run('TYPES.descanso.bg'));assert(!grid.includes('day-symbol'));});
